homeassistant:
  customize:
     sensor.28051686b8acff:
        friendly_name:  fttemp
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.3697
  longitude: -122.0214
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 29
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

mqtt:
  broker: 192.168.1.188
  port: 1883
  keepalive: 60
#  client_id: hass_fishtank
#  username: homeassistant
#  password: !secret hass_password

mqtt_eventstream:
  publish_topic: slaves/upstairs/doors

switch:
  - platform: mqtt
    name: "Skimmer"
    state_topic: "fishtank/skimmer/state" 
    command_topic: "fishtank/skimmer/command" 
#    availability_topic: "fishtank/skimmer/get" 
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "Fan"
    state_topic: "fishtank/fan/state" 
    command_topic: "fishtank/fan/command" 
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "Pumps"
    state_topic: "fishtank/pumps/state" 
    command_topic: "fishtank/pumps/command" 
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "refillpump"
    state_topic: "fishtank/refillpump/state" 
    command_topic: "fishtank/refillpump/command" 
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
#  - platform: rpi_gpio
#    invert_logic: false
#    ports:
#       21:  Protein Skimmer
#       20:  Powerhead Sicce
#       16:  Refill Resevoir


http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: onewire
    

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
